Add URDF Tutorial - Differential Drive Robot
ros-planning/navigation2_tutorials pull request #19
Opened 2020-12-21 08:24 UTC by jd-deleon

2020-12-21 08:27 UTC, jd-deleon commented
Also a contribution towards the completion of ros-planning/navigation2#1589

2020-12-21 15:56 UTC, SteveMacenski approved these changes

2020-12-21 15:57 UTC, SteveMacenski requested changes

2020-12-21 15:57 UTC, SteveMacenski commented on nav2_urdf_setup/CMakeLists.txt
> +project(sam_bot_description)
The package should be `sam_bot_description` rather than `nav2_urdf_setup` so that they match

2021-01-04 02:17 UTC, jd-deleon commented
Done. Directory changed to match package name

2021-01-04 19:01 UTC, SteveMacenski approved these changes

2021-01-04 19:01 UTC, merged